import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import DarkTh from "@/components/DarkTh";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      > 
     
      <div style={{position:'fixed', bottom:0, padding:10}}>
      <DarkTh   />
      </div>
      {children}

      </ThemeProvider>
      </body>
    </html>
  );
}
